apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: patricklaabs
  namespace: grpc
spec:
  chart:
    spec:
      version: ">=0.1.0"
  values:
    ingress:
      hosts:
        - host: grpc.production.com
          paths:
            - path: /
              pathType: ImplementationSpecific
