apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources: |
  - ../base/podinfo
  - ../base/restfulgo
patchesStrategicMerge: |
  - podinfo-values.yaml
  - restfulgo-values.yaml
